steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/board-frontend/react-web:latest", "./docker/production/"]
  images:
    - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/board-frontend/react-web:latest"