steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast1-docker.pkg.dev/board-357514/board-frontend/react-web", "-f", "./docker/production/Dockerfile", "."]
images:
  - "asia-northeast1-docker.pkg.dev/board-357514/board-frontend/react-web"
logsBucket: 'gs://board-357514_cloudbuild-frontend-log'