version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      - board_default
    command: >
      sh -c
      "echo 'REACT_APP_WEB_ENV=development' > .env &&
      yarn start"
    environment:
      - VIRTUAL_HOST=web.localhost.test
      - VIRTUAL_PORT=3000

networks:
  board_default:
    external: true
