steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_BACKEND_REPO}/${_GO_API_IMAGE}", "-f", "./docker/api/production/Dockerfile",
           "--build-arg", "MYSQL_PASSWORD=${_MYSQL_PASSWORD}", "--build-arg", "SESSION_SECRET=${_SESSION_SECRET}", "."]
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/${_BACKEND_REPO}/${_GO_API_IMAGE}"
logsBucket: 'gs://${_BACKEND_BUCKET}'