steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/board-backend/go-api:latest", "./docker/api/production/"]
  images:
    - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/board-backend/go-api:latest"