version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.2
  
executors:
  go:
    docker:
      - image: cimg/go:1.18

jobs:
  go-test:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          working_directory: ./backend
          command: |
            go test ./...
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: go-mod-v4-{{ checksum "go.sum" }}

  react-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./frontend
          pkg-manager: yarn
      - run:
          working_directory: ./frontend
          command: |
            yarn test

  go-build:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud builds submit --config=backend/cloudbuild.yaml backend \
            --substitutions=_MYSQL_PASSWORD=${MYSQL_PASSWORD},_SESSION_SECRET=${SESSION_SECRET},_BACKEND_SERVICE=${BACKEND_SERVICE},_GO_API_IMAGE=${GO_API_IMAGE}
  
  db-migration-build:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud builds submit --config=backend/docker/migration/cloudbuild.yaml backend/docker/migration \
            --substitutions=_MYSQL_PASSWORD=${MYSQL_PASSWORD},_BACKEND_SERVICE=${BACKEND_SERVICE},_DB_MIGRATION_IMAGE=${DB_MIGRATION_IMAGE}
  
  react-build:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            echo 'REACT_APP_WEB_ENV=production' > frontend/.env
            gcloud builds submit --config=frontend/cloudbuild.yaml frontend \
            --substitutions=_FRONTEND_SERVICE=${FRONTEND_SERVICE},_REACT_WEB_IMAGE=${REACT_WEB_IMAGE}
  
  backend-deploy:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud run deploy board-api-service --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${BACKEND_SERVICE}/${GO_API_IMAGE}:latest
  
  frontend-deploy:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud run deploy board-api-service --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${FRONTEND_SERVICE}/${REACT_WEB_IMAGE}:latest
  
  db-migration:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud beta run jobs update db-migration-job --region ${REGION} --image ${REGION}-docker.pkg.dev/${PROJECT_ID}/${BACKEND_SERVICE}/${DB_MIGRATION_IMAGE}:latest
            gcloud beta run jobs execute db-migration-job --region ${REGION} --wait

workflows:
  production-deploy:
   jobs:
     - go-test
     - react-test
     - go-build:
         requires:
           - go-test
           - react-test
     - db-migration-build:
         requires:
           - go-test
           - react-test
     - react-build:
         requires:
           - go-test
           - react-test
     - db-migration:
         requires:
           - go-build
           - db-migration-build
           - react-build
     - backend-deploy:
         requires:
           - db-migration
     - frontend-deploy:
         requires:
           - db-migration