version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  node: circleci/node@5.0.2
  
executors:
  go:
    docker:
      - image: cimg/go:1.18

jobs:
  go-test:
    executor: go
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          working_directory: ./backend
          command: |
            go test ./...
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: go-mod-v4-{{ checksum "go.sum" }}

  react-test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./frontend
          pkg-manager: yarn
      - run:
          working_directory: ./frontend
          command: |
            yarn test

  go-build:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud builds submit --region=asia-northeast1 --config=./backend/cloudbuild.yaml
  
  react-build:
    executor: gcp-cli/google
    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          command: |
            gcloud builds submit --region=asia-northeast1 --config=./frontend/cloudbuild.yaml

workflows:
  production-deploy:
   jobs:
     - go-test
     - react-test
     - go-build:
         requires:
           - go-test
           - react-test
     - react-build:
         requires:
           - go-test
           - react-test