version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.1
  
executors:
  go:
    docker:
      - image: cimg/go:1.18
  node:
    docker:
      - image: cimg/node:16.14

jobs:
  go-test:
    executor: go
    working_directory: ./backend
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: go test ./...
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: go-mod-v4-{{ checksum "go.sum" }}

workflows:
  production-deploy:
   jobs:
     - go-test