// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/visitor_repo.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/jumpei00/board/backend/app/domain"
)

// MockVisitorRepository is a mock of VisitorRepository interface.
type MockVisitorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVisitorRepositoryMockRecorder
}

// MockVisitorRepositoryMockRecorder is the mock recorder for MockVisitorRepository.
type MockVisitorRepositoryMockRecorder struct {
	mock *MockVisitorRepository
}

// NewMockVisitorRepository creates a new mock instance.
func NewMockVisitorRepository(ctrl *gomock.Controller) *MockVisitorRepository {
	mock := &MockVisitorRepository{ctrl: ctrl}
	mock.recorder = &MockVisitorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVisitorRepository) EXPECT() *MockVisitorRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockVisitorRepository) Get() (*domain.Visitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(*domain.Visitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVisitorRepositoryMockRecorder) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVisitorRepository)(nil).Get))
}

// Update mocks base method.
func (m *MockVisitorRepository) Update(visitors *domain.Visitor) (*domain.Visitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", visitors)
	ret0, _ := ret[0].(*domain.Visitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVisitorRepositoryMockRecorder) Update(visitors interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVisitorRepository)(nil).Update), visitors)
}
