steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast1-docker.pkg.dev/board-357514/board-backend/db-migration", "."]
images:
  - "asia-northeast1-docker.pkg.dev/board-357514/board-backend/db-migration"
logsBucket: 'gs://board-357514_cloudbuild-migration-log'