development:
  dialect: mysql
  datasource: development:password@tcp(mysql:3306)/board?charset=utf8mb4&parseTime=True
  dir: ./mysql

production:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_PROTOCOL}(${MYSQL_HOST})/${MYSQL_DATABASE_NAME}?charset=utf8mb4&parseTime=True
  dir: ./mysql
