name: Reviewdog

on:
  pull_request:
    branches-ignore:
      - main
    types:
      - opened
      - synchronize

jobs:
  backend-golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yaml"
          level: warning
          workdir: backend/
          reporter: github-pr-review
          fail_on_error: true
          go_version: "1.18"
  frontend-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
      - name: install modules
        run: |
          yarn install
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          level: warning
          reporter: github-pr-review
          fail_on_error: true
          workdir: frontend/
          eslint_flags: "--config=.eslintrc.json ./src/**/*.{ts,tsx}"