name: Reviewdog

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  frontend-eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ github.token }}
          level: warning
          reporter: github-pr-check
          workdir: frontend/
          eslint_flags: "./src/**/*.{ts,tsx} ./src/*.{ts,tsx}"